"""Initial migration

Revision ID: 2ad6349594cb
Revises: 
Create Date: 2025-05-11 17:55:22.547388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad6349594cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('field_name_ar', sa.String(length=50), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name'),
    sa.UniqueConstraint('field_name', name='uq_display_settings_field_name')
    )
    op.create_table('tblcourt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_court_name')
    )
    op.create_table('tbluser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['tblcourt.id'], name='fk_user_court', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('tblcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_date', sa.Date(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('c_order', sa.Integer(), nullable=False),
    sa.Column('next_session_date', sa.String(length=100), nullable=True),
    sa.Column('session_result', sa.Text(), nullable=True),
    sa.Column('num_sessions', sa.Integer(), nullable=False),
    sa.Column('case_subject', sa.String(length=200), nullable=True),
    sa.Column('defendant', sa.String(length=100), nullable=True),
    sa.Column('plaintiff', sa.String(length=100), nullable=True),
    sa.Column('prosecution_number', sa.String(length=50), nullable=True),
    sa.Column('police_department', sa.String(length=150), nullable=True),
    sa.Column('police_case_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'finished', 'postponed', 'in_session', name='casestatus'), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['tblcourt.id'], name='fk_case_court', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbluser.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number', name='uq_case_number')
    )
    op.create_table('tbldisply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('custom_order', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tblcase.id'], name='fk_display_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['tblcourt.id'], name='fk_display_court', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbldisply')
    op.drop_table('tblcase')
    op.drop_table('tbluser')
    op.drop_table('tblcourt')
    op.drop_table('display_settings')
    # ### end Alembic commands ###
