
"""Add ActivityLog table

Revision ID: 613a08f7ad73
Revises: 65d748e58265
Create Date: 2025-06-09 15:13:07.587822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613a08f7ad73'
down_revision = '65d748e58265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblactivity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tblcase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['tblcourt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbluser.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblactivity_log')
    # ### end Alembic commands ###
