"""Initial migration

Revision ID: 65d748e58265
Revises: 2ad6349594cb
Create Date: 2025-05-11 18:13:43.666357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d748e58265'
down_revision = '2ad6349594cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_display_settings_field_name', ['field_name'])

    with op.batch_alter_table('tblcourt', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_court_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblcourt', schema=None) as batch_op:
        batch_op.drop_constraint('uq_court_name', type_='unique')

    with op.batch_alter_table('display_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_display_settings_field_name', type_='unique')

    # ### end Alembic commands ###
